export const dare = [
    "Zatańcz przez 30 sekund.",
    "Pokaż wszystkim swoje najzabawniejsze zdjęcie.",
    "Zrób 10 pompek.",
    "Zaśpiewaj swoją ulubioną piosenkę.",
    "Spróbuj zrobić 10 przysiadów bez przerwy.",
    "Zrób zdjęcie swojej twarzy z jakimś zabawnym wyrazem.",
    "Pokaż wszystkim swój taniec, który nauczyłeś się w szkole.",
    "Przebierz się w coś szalonego na 5 minut.",
    "Zadzwoń do znajomego i zaśpiewaj mu piosenkę.",
    "Zaśpiewaj i zatańcz do kawałka, który właśnie leci w tle.",
    "Powiedz alfabet wspak.",
    "Udawaj kurczaka przez 1 minutę.",
    "Narysuj coś z zamkniętymi oczami.",
    "Mów śmiesznym głosem przez 2 minuty.",
    "Zrób minę jakbyś wygrał milion.",
    "Zaproś losową osobę z pokoju na randkę (dla żartu!).",
    "Zamień się telefonem z osobą po lewej na 1 minutę.",
    "Powiedz coś miłego każdej osobie przy stole.",
    "Przynieś coś z lodówki z zawiązanymi oczami.",
    "Zatańcz jak robot przez 30 sekund.",
    "Wymyśl piosenkę o kimś w pokoju.",
    "Zjedz plasterek cytryny bez grymasu.",
    "Zrób sobie wąsy z jedzenia.",
    "Zrób śmieszną relację na Instagramie.",
    "Pokaż swoją ostatnią wiadomość na Messengerze.",
    "Zamień się ubraniem z kimś na 2 minuty.",
    "Mów tylko szeptem przez następną rundę.",
    "Zaproponuj nową karę do tej gry.",
    "Zadzwoń do kogoś z kontaktów i powiedz „kocham Cię” i się rozłącz.",
    "Powiedz 3 rzeczy, które kochasz w sobie.",
    "Zrób TikToka teraz (nawet jeśli nie opublikujesz).",
    "Przez 30 sekund bądź manekinem – nie ruszaj się.",
    "Zamknij oczy i zgadnij, co ktoś Ci poda do powąchania.",
    "Wymyśl rymowankę z imieniem osoby po prawej.",
    "Udawaj znaną osobę przez minutę.",
    "Zaprojektuj nowy taniec i pokaż go wszystkim.",
    "Używaj wyrazu „ziemniak” w każdej swojej wypowiedzi do końca rundy.",
    "Ugryź plaster cebuli.",
    "Zmień fryzurę przy pomocy wody i ręki – nowy look!",
    "Załóż coś odwrócone tyłem do przodu i nie komentuj tego.",
    "Zrób pokaz mody z rzeczami, które masz pod ręką.",
    "Napisz zabawną wiadomość do rodzica (ale bez obrazy!).",
    "Zadzwoń do pizzerii i zapytaj, czy mają sushi.",
    "Zrób 3 przysiady i za każdym razem krzyknij „TAK!”",
    "Zamień się miejscem z osobą naprzeciwko na jedną rundę.",
    "Przez minutę mów tylko po angielsku (albo udawaj!).",
    "Wymyśl nową karę do tej gry i zrób ją sam!",
    "Udawaj, że jesteś prezenterem pogody przez 30 sekund.",
    "Opowiedz żart. Jak nikogo nie rozśmieszy – kara!"
];
