export const neverEverQuestions = [
    "Nigdy przenigdy nie zaspa³em na wa¿ne spotkanie.",
    "Nigdy przenigdy nie jad³em œlimaków.",
    "Nigdy przenigdy nie z³ama³em koœci.",
    "Nigdy przenigdy nie k³ama³em w CV.",
    "Nigdy przenigdy nie ogl¹da³em ca³ego sezonu w jeden dzieñ.",
    "Nigdy przenigdy nie œmia³em siê tak bardzo, ¿e pop³aka³em siê.",
    "Nigdy przenigdy nie udawa³em chorego, ¿eby nie iœæ do szko³y/pracy.",
    "Nigdy przenigdy nie zapomnia³em czyichœ urodzin.",
    "Nigdy przenigdy nie wys³a³em wiadomoœci do niew³aœciwej osoby.",
    "Nigdy przenigdy nie zrobi³em sobie selfie w ³azience.",
    "Nigdy przenigdy nie obla³em egzaminu.",
    "Nigdy przenigdy nie jad³em czegoœ po terminie.",
    "Nigdy przenigdy nie pods³uchiwa³em rozmowy.",
    "Nigdy przenigdy nie by³em zakochany w nauczycielu.",
    "Nigdy przenigdy nie by³em w szpitalu jako pacjent.",
    "Nigdy przenigdy nie zgubi³em portfela.",
    "Nigdy przenigdy nie by³em na koncercie.",
    "Nigdy przenigdy nie wyda³em ca³ej wyp³aty w jeden dzieñ.",
    "Nigdy przenigdy nie zapomnia³em, gdzie zaparkowa³em samochód.",
    "Nigdy przenigdy nie mia³em kaca.",
    "Nigdy przenigdy nie p³aka³em na filmie.",
    "Nigdy przenigdy nie krad³em niczego ze sklepu.",
    "Nigdy przenigdy nie œpiewa³em karaoke publicznie.",
    "Nigdy przenigdy nie pisa³em œci¹gi.",
    "Nigdy przenigdy nie jecha³em bez biletu.",
    "Nigdy przenigdy nie zasn¹³em w miejscu publicznym.",
    "Nigdy przenigdy nie wpad³em do basenu ubrany.",
    "Nigdy przenigdy nie rozbi³em telefonu.",
    "Nigdy przenigdy nie mówi³em komuœ „kocham ciê”, nie maj¹c tego na myœli.",
    "Nigdy przenigdy nie próbowa³em nauczyæ siê tañca z TikToka.",
    "Nigdy przenigdy nie przegapi³em samolotu/poci¹gu.",
    "Nigdy przenigdy nie mia³em ¿enuj¹cego przejêzyczenia publicznie.",
    "Nigdy przenigdy nie zjad³em ca³ej pizzy sam.",
    "Nigdy przenigdy nie korzysta³em z aplikacji randkowej.",
    "Nigdy przenigdy nie zosta³em poproszony o dowód w sklepie.",
    "Nigdy przenigdy nie p³aka³em przez serial.",
    "Nigdy przenigdy nie mia³em z³amanej rêki/nogi.",
    "Nigdy przenigdy nie wyszed³em z domu w kapciach przez pomy³kê.",
    "Nigdy przenigdy nie mówi³em do siebie na g³os.",
    "Nigdy przenigdy nie sprawdza³em czyjegoœ Instagrama z fejkowego konta.",
    "Nigdy przenigdy nie udawa³em, ¿e rozumiem, chocia¿ nie mia³em pojêcia.",
    "Nigdy przenigdy nie kupi³em czegoœ i od razu tego nie ¿a³owa³em.",
    "Nigdy przenigdy nie mia³em przygody z farbowaniem w³osów w domu.",
    "Nigdy przenigdy nie udawa³em, ¿e nie widzê kogoœ znajomego na ulicy.",
    "Nigdy przenigdy nie rozla³em picia na wa¿ne dokumenty.",
    "Nigdy przenigdy nie zgubi³em kluczy.",
    "Nigdy przenigdy nie zrobi³em dziwnej miny na zdjêciu klasowym.",
    "Nigdy przenigdy nie œpiewa³em w prysznicu.",
    "Nigdy przenigdy nie mówi³em przez sen.",
    "Nigdy przenigdy nie mia³em œmiesznego przezwiska.",
    "Nigdy przenigdy nie biega³em w deszczu dla zabawy.",
    "Nigdy przenigdy nie zakocha³em siê w kimœ poznanym online.",
    "Nigdy przenigdy nie wzi¹³em jedzenia znajomego bez pytania.",
    "Nigdy przenigdy nie zasn¹³em na lekcji/zajêciach.",
    "Nigdy przenigdy nie napisa³em czegoœ ¿enuj¹cego w zeszycie/kartce i ktoœ to przeczyta³.",
    "Nigdy przenigdy nie zapomnia³em o randce lub spotkaniu.",
    "Nigdy przenigdy nie pomyli³em imienia drugiej osoby.",
    "Nigdy przenigdy nie by³em w klubie.",
    "Nigdy przenigdy nie dosta³em mandatu.",
    "Nigdy przenigdy nie próbowa³em zrobiæ czegoœ ekstremalnego, np. skoku na bungee.",
    "Nigdy przenigdy nie zrobi³em sobie zdjêcia z celebryt¹.",
    "Nigdy przenigdy nie zgubi³em siê w innym mieœcie.",
    "Nigdy przenigdy nie zapomnia³em kodu do telefonu.",
    "Nigdy przenigdy nie zapomnia³em tekstu piosenki w trakcie œpiewania.",
    "Nigdy przenigdy nie przebra³em siê za coœ dziwnego na imprezê.",
    "Nigdy przenigdy nie napisa³em czegoœ g³upiego w statusie na Facebooku.",
    "Nigdy przenigdy nie nagra³em TikToka i nigdy go nie opublikowa³em.",
    "Nigdy przenigdy nie powiedzia³em „kocham ciê” przypadkowo do nauczyciela/rodzica znajomego.",
    "Nigdy przenigdy nie robi³em zdjêcia jedzenia w restauracji.",
    "Nigdy przenigdy nie zrobi³em screena czatu i wys³a³em go tej osobie przez przypadek.",
    "Nigdy przenigdy nie kupi³em czegoœ pod wp³ywem impulsu online.",
    "Nigdy przenigdy nie zgubi³em siê w centrum handlowym.",
    "Nigdy przenigdy nie próbowa³em udawaæ inny akcent.",
    "Nigdy przenigdy nie zjad³em coœ, co upad³o na ziemiê.",
    "Nigdy przenigdy nie powiedzia³em komuœ komplementu tylko po to, ¿eby coœ dostaæ.",
    "Nigdy przenigdy nie wzi¹³em udzia³u w wyzwaniu internetowym.",
    "Nigdy przenigdy nie udawa³em, ¿e jestem zajêty, ¿eby z kimœ nie gadaæ.",
    "Nigdy przenigdy nie powiedzia³em „kocham ciê” komuœ zbyt wczeœnie.",
    "Nigdy przenigdy nie zrobi³em komuœ psikusa.",
    "Nigdy przenigdy nie mia³em crush'a na nauczyciela.",
    "Nigdy przenigdy nie pomyli³em siê w czyimœ imieniu w wiadomoœci.",
    "Nigdy przenigdy nie by³em wybrany ostatni do dru¿yny.",
    "Nigdy przenigdy nie straci³em czegoœ wa¿nego na wakacjach.",
    "Nigdy przenigdy nie z³ama³em jakiejœ regu³y tylko dlatego, ¿e 'wszyscy tak robi¹'.",
    "Nigdy przenigdy nie powiedzia³em, ¿e obejrza³em film, którego nie widzia³em.",
    "Nigdy przenigdy nie opublikowa³em posta i od razu go usun¹³em.",
    "Nigdy przenigdy nie by³em tak zmêczony, ¿e zasn¹³em w ubraniach.",
    "Nigdy przenigdy nie spóŸni³em siê wiêcej ni¿ godzinê.",
    "Nigdy przenigdy nie zrobi³em sobie kompromituj¹cego zdjêcia i wys³a³em komuœ przez przypadek.",
    "Nigdy przenigdy nie zjad³em dziwnej potrawy tylko z grzecznoœci.",
    "Nigdy przenigdy nie zapomnia³em, co mia³em powiedzieæ podczas prezentacji.",
    "Nigdy przenigdy nie z³o¿y³em ¿yczeñ urodzinowych dzieñ za póŸno.",
    "Nigdy przenigdy nie by³em w centrum uwagi niechc¹cy.",
    "Nigdy przenigdy nie udawa³em, ¿e nie s³yszê telefonu.",
    "Nigdy przenigdy nie próbowa³em udawaæ, ¿e nie jestem zazdrosny.",
    "Nigdy przenigdy nie udostêpni³em czegoœ publicznie przez przypadek."
];
