export const truthQuestion = [
    "Jaki jest Twój ulubiony film?",
    "Jakie jest Twoje najwiêksze marzenie?",
    "Co by³oby Twoim wymarzonym zawodem?",
    "Jakie jest Twoje najdziwniejsze wspomnienie?",
    "Co najbardziej cenisz w przyjaŸni?",
    "Jaka jest Twoja najgorsza cecha?",
    "Co byœ zmieni³ w swoim ¿yciu, gdybyœ mia³ szansê?",
    "Jakie jest Twoje najwiêksze osi¹gniêcie?",
    "Jaka jest Twoja najgorsza wada?",
    "Kogo podziwiasz najbardziej?",
    "Czy kiedykolwiek sk³ama³eœ przyjacielowi?",
    "Czy mia³eœ kiedyœ z³amane serce?",
    "Kto jest Twoim sekretnym zauroczeniem?",
    "Czy masz jak¹œ skryt¹ pasjê?",
    "Jakie jest Twoje najwiêksze zawstydzenie?",
    "Czy kiedykolwiek z³ama³eœ prawo?",
    "Czego siê najbardziej boisz?",
    "Jakie jest Twoje najwiêksze marzenie z dzieciñstwa?",
    "Jakie jest Twoje najwiêksze rozczarowanie?",
    "Czy kiedykolwiek zdradzi³eœ czyjeœ zaufanie?",
    "Co byœ zrobi³, gdybyœ wygra³ milion z³otych?",
    "Jak¹ rzecz najbardziej ¿a³ujesz, ¿e zrobi³eœ?",
    "Czy by³ ktoœ, kogo skrzywdzi³eœ i ¿a³ujesz?",
    "Jakie k³amstwo ostatnio powiedzia³eœ?",
    "Co jest Twoim najwiêkszym kompleksem?",
    "Jaki by³ Twój najgorszy dzieñ w ¿yciu?",
    "Czy kiedykolwiek kogoœ ok³ama³eœ dla w³asnej korzyœci?",
    "Jak wygl¹da³by Twój idealny dzieñ?",
    "Kogo lub co byœ zabra³ na bezludn¹ wyspê?",
    "Czego nigdy byœ nie zrobi³ – nawet za milion?",
    "Co najbardziej cenisz w sobie?",
    "Czy mia³eœ kiedyœ konflikt z blisk¹ osob¹?",
    "Jak¹ plotkê o sobie s³ysza³eœ?",
    "Czy masz jakieœ sekrety, których nikt nie zna?",
    "Jak¹ najg³upsz¹ rzecz zrobi³eœ z mi³oœci?",
    "Jakie pytanie chcia³byœ, ¿eby Ci NIGDY nie zadano?",
    "Czy by³eœ kiedyœ zazdrosny o sukces znajomego?",
    "Czego najbardziej siê wstydzisz z przesz³oœci?",
    "Jaki jest Twój najwiêkszy lêk w relacjach?",
    "Czy udawa³eœ kiedyœ coœ, ¿eby siê komuœ przypodobaæ?",
    "Gdybyœ móg³ cofn¹æ czas, do jakiego momentu byœ wróci³?",
    "Czy kiedykolwiek chcia³eœ zmieniæ swoje imiê?",
    "Co najbardziej stresuje Ciê w ¿yciu?",
    "Czy kiedykolwiek ¿a³owa³eœ, ¿e kogoœ pozna³eœ?",
    "Czy zakocha³eœ siê w kimœ, kto Ciê nie zna³?",
    "Czy mia³eœ kiedyœ fa³szywego przyjaciela?",
    "Czy ktoœ kiedykolwiek Ciê zdradzi³?",
    "Gdybyœ mia³ jedno ¿yczenie – co by to by³o?",
    "Co Ciê naprawdê uszczêœliwia?",
    "Jak myœlisz – jak widz¹ Ciê inni ludzie?"
];
